### ISSUE TITLE
Enable CI build

### ISSUE THREAD

**Issue by shawnps** [ausocean/h264decode#31]
@saxon-milton I'm quite familiar with Travis-CI. If that's okay with you, please log in to https://travis-ci.org with your GitHub account and enable the `ausocean/h264decode` repo. I can take care of adding the `.travis.yml` after that.

I'm not able to enable the repo on Travis since I'm not an owner.

**Comment by saxon-milton** [comment]
@shawnps @scruzin with have to enable Travis (ausocean is code owner, and is managed by Alan). Are you okay with Travis Alan ?

**Comment by saxon-milton** [comment]
@shawnps this can be closed now ?

**Comment by shawnps** [comment]
@saxon-milton we may need some more setup - I don't see any builds here:

https://travis-ci.org/ausocean/h264decode

For example, it should have built your PR: https://github.com/ausocean/h264decode/pull/36

It might be caused by the transition of the ausocean user to GitHub organization. Maybe Alan could take another look?

Edit: I was able to manually trigger the build in the Travis UI, but I'm still unclear on why it didn't build your PR. I'll keep digging.

**Comment by shawnps** [comment]
I've reached out to Travis-CI support about this, will post back with details when I get a response.

**Comment by saxon-milton** [comment]
@shawnps ahh I see, no worries. Cheers for looking into it.

**Comment by shawnps** [comment]
Looks good now
